/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package whispir.test.java;
import org.whispir.api.MessagesApi;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        MessagesApi api = new MessagesApi();
        System.out.println(api);
    }
}
