/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package whispir.test.java;

import whispir_sdk_java.ApiClient;
import org.whispir.api.AuthApi;
import org.whispir.api.MessagesApi;
import org.openapitools.client.model.PostAuth200Response;
import org.openapitools.client.model.Message;

import io.github.cdimascio.dotenv.Dotenv;
import whispir_sdk_java.utils.WrapperInit;
import whispir_wrapped_java.Client;
import whispir_wrapped_java.MessageClient;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static WrapperInit wrapperInit() {
        WrapperInit wrapper = new WrapperInit();
        Dotenv dotenv = Dotenv.load();
        wrapper.setInitValues(dotenv.get("API_KEY"), 
                "application/vnd.whispir.auth-v1+json", 
                "application/vnd.whispir.auth-v1+json");
        
        return wrapper;
    }

    // creates an API client
    // setting up the API URL and Whispir username and password
    public static ApiClient createClient() {
        ApiClient client;
        client = new ApiClient();
        Dotenv dotenv = Dotenv.load();

        String API_URL = dotenv.get("API_URL");

        client.setBasePath(API_URL);
        client.setUsername(dotenv.get("WHISPIR_USERNAME"));
        client.setPassword(dotenv.get("WHISPIR_PASSWORD"));
        return client;
    }

    public static void generateAuthToken() {
        ApiClient client = createClient();
        // initialize Auth API
        AuthApi authApi = new AuthApi(client);
        Dotenv dotenv = Dotenv.load();
        try {
            // performs an Auth API post to request for token
            PostAuth200Response response = authApi.postAuth(
                    dotenv.get("API_KEY"),
                    "application/vnd.whispir.auth-v1+json",
                    "application/vnd.whispir.auth-v1+json");
            System.out.println(response);
        } catch (Exception e) {
            // TODO: handle exception
            System.out.println(e);
        }
    }

    public static void postMessage() {
        Dotenv dotenv = Dotenv.load();
        Client apiClient = new Client( dotenv.get("API_URL"),
                dotenv.get("WHISPIR_USERNAME"),
                dotenv.get("WHISPIR_PASSWORD"),
                        dotenv.get("WORKSPACE_ID"));
        // initialize Message API
        MessageClient clientMessage = apiClient.MessageClient();
////        MessageClient messageClient = new MessageClient(
////                dotenv.get("WHISPIR_USERNAME"),
////                dotenv.get("WHISPIR_PASSWORD"),
////                dotenv.get("API_URL"),
////                dotenv.get("WORKSPACE_ID")
////        );
        Message message = new Message();
        
        
        // initialize message with params
        message.to("052215685521");
        message.subject("Hi there!");
        message.body("Hello, this is a test");
        

        try {
            // performs a Message API call
//             Message response = messageApi.postMessages(dotenv.get("WORKSPACE_ID"),
//             wrapper.getApiKey(),/Users/carlangeloorale/Documents/programming/whispir/openapi/whispir-test-java/app/.env
//             wrapper.getContentType(),
//             wrapper.getAccept(), 
//             message);
               Message response = apiClient.MessageClient().postMessage(message, dotenv.get("API_KEY"));
             System.out.println(response);
        } catch (Exception e) {
            // TODO: handle exception
            System.out.println(e);
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Dotenv dotenv = Dotenv.load();
        generateAuthToken();
        postMessage();
    }
}
