/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package whispir.test.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

 import org.whispir.api.MessagesApi;

class AppTest {

    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();

        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
