/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The event object.
*/
export class Event {
    /**
    * Specifies the name of the label used for the messages sent under this event
    */
    'eventLabel': string;
    /**
    * Specifies the status of the event. The status can be one of <ul><li>Active</li><li>Resolved<l></ul>Note:The default status is Open.
    */
    'status': string;
    /**
    * Specifies the summary of the event. A single liner that can be equivalent to the Subject of an email.
    */
    'summary'?: string;
    /**
    * Specifies the detailed description of the event
    */
    'description': string;
    /**
    * Specifies the latitude, longitude values of the event location. This helps to show the event location on Whispir’s geo-map feature set and coordinated communication based on the geo location of the event.
    */
    'location'?: string;
    /**
    * Specifies the startdate of the event. This is a mandatory value.The date should be in the format of DD/MM/YYYY HH:MI:SS in 24hrs format. e.g 11/09/2015 17:21:00 for 11th September 2015 5.21 PM.
    */
    'startDate'?: string;
    /**
    * Specifies the endDate of the event.The date should be in the format of DD/MM/YYYY HH:MI:SS in 24hrs format. e.g. 11/09/2015 19:26:00 for 11th September 2015 7.26 PM.
    */
    'endDate'?: string;
    /**
    * Specifies the severity of the event. While this can change from company to company, the standard value set to be chosen from is <ul><li>Severity 5 - Routine Maintenance Tasks</li><li>Severity 4 - Scheduled System Changes</li><li>Severity SL3 - Minor Outage (Some Service Degradation)</li><li>Severity SL2 - Moderate Outage (Service Degradation)</li><li>Severity SL1 - Major Outage (Significant Service Unavailablity)</li><ul>
    */
    'severity'?: string;
    /**
    * Specifies the priority of the event. While this can change from company to company, the standard value set to be chosen from is <ul><li>Priority 5 - No Set Resolution Period</li><li>Priority 4 - <1 week Resolution</li><li>Priority 3 - <3 day Resolution</li><li>Priority 2 - <1 day Resolution</li><li>Priority 1 - <2hr Resolution</li></ul>
    */
    'priority'?: string;
    /**
    * The duration of the event in HH:MI:SS. e.g. 02:05:00 This can be substituted in the place of end date if required. Or a subset of the time between the start and end Dates.
    */
    'duration'?: string;
    /**
    * Specifies the category of event. The default values to choose from are <ul><li>Internal Systems</li><li>External Systems</li><li>Infrasturcture</li></ul>
    */
    'category'?: string;
    /**
    * Specifies the subcategory in the category. The default values to choose from are <ul><li>Customer Impact</li><li>Cust & Staff Impact</li><li>Staff Impact</li><li>Impact Unknown</li></ul>
    */
    'subcategory'?: string;
    /**
    * Specifies the type of event. The default values to choose from are <ul><li>Multiple Issues</li><li>NIL</li><li>Network</li><li>Applications</li><li>Mobile Apps</li></ul>
    */
    'type'?: string;
    /**
    * Specifies the name/contact who is the external vendor related to this event
    */
    'externalVendor'?: string;
    /**
    * Specifies the line Number (production lines)
    */
    'lineNumber'?: string;
    /**
    * Specifies the number as tracked by an external party realted to this event
    */
    'externalCaseNumber'?: string;
    /**
    * Specifies the platform in the company to which this event is associated with
    */
    'platform'?: string;
    /**
    * Specifies the service in the company to which this event is associated with
    */
    'services'?: string;
    /**
    * Specifies the impact condition of this event to the company. These values can be configured via custom lists as these can be very specific to the company. The default list to choose from are - <ul><li>All services not available</li><li>All services degraded</li><li>Some services not available</li><li>Some services degraded</li><li>No Impact</li><li>Unknown</li></ul>
    */
    'impactCondition'?: string;
    /**
    * Specifies the impact of this event to the Organization. These values can be configured via custom lists as these can be very specific to the company. The default list to choose from are - <ul><li>Global</li><li>National</li><li>Local</li></ul>
    */
    'impactToOrg'?: string;
    /**
    * Specifies the impact location of this event to the Organization’s operational geographies. These values can be configured via custom lists as these can be very specific to the company.
    */
    'locations'?: string;
    /**
    * Specifies the set of individual actions to be taken during this event.Each action consists of - <ul><li>actionDate - the start date of this action in dd/mm/yyyy HH:MI:SS 24hr format </li><li>actionOwner - the individual (contact) responsible for this action’s execution</li><li>actionDetails - the detail description of this action</li></ul><p>An event can have a maximum of 10 action. So the action values are numbered. actionDate1, actionOwner1, actionDetails1, actionDate2, actionOwner2, actionDetails2 …actionDate10, actionOwner10, actionDetails10
    */
    'multipleKeyValueSets'?: string;
    /**
    * The other (alias) name and title fields 1) otherFirstName, otherLastName, otherTitle
    */
    'aliasFields'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eventLabel",
            "baseName": "eventLabel",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "severity",
            "baseName": "severity",
            "type": "string"
        },
        {
            "name": "priority",
            "baseName": "Priority",
            "type": "string"
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "string"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string"
        },
        {
            "name": "subcategory",
            "baseName": "subcategory",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "externalVendor",
            "baseName": "externalVendor",
            "type": "string"
        },
        {
            "name": "lineNumber",
            "baseName": "lineNumber",
            "type": "string"
        },
        {
            "name": "externalCaseNumber",
            "baseName": "externalCaseNumber",
            "type": "string"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string"
        },
        {
            "name": "services",
            "baseName": "services",
            "type": "string"
        },
        {
            "name": "impactCondition",
            "baseName": "impactCondition",
            "type": "string"
        },
        {
            "name": "impactToOrg",
            "baseName": "impactToOrg",
            "type": "string"
        },
        {
            "name": "locations",
            "baseName": "locations",
            "type": "string"
        },
        {
            "name": "multipleKeyValueSets",
            "baseName": "multiple key value sets",
            "type": "string"
        },
        {
            "name": "aliasFields",
            "baseName": "Alias Fields",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Event.attributeTypeMap;
    }
}

