/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The object defining options for push messages.
*/
export class FeaturesPushOptions {
    /**
    * A flag indicating whether notifications should be enabled for message replies.
    */
    'notifications'?: FeaturesPushOptions.NotificationsEnum;
    /**
    * The number of minutes to wait for a reply until escalating to the next contact.
    */
    'escalationMins'?: string;
    /**
    * The identifier for the registered application.
    */
    'appId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "notifications",
            "baseName": "notifications",
            "type": "FeaturesPushOptions.NotificationsEnum"
        },
        {
            "name": "escalationMins",
            "baseName": "escalationMins",
            "type": "string"
        },
        {
            "name": "appId",
            "baseName": "appId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FeaturesPushOptions.attributeTypeMap;
    }
}

export namespace FeaturesPushOptions {
    export enum NotificationsEnum {
        Enabled = <any> 'enabled',
        Disabled = <any> 'disabled'
    }
}
