/**
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FieldMapping } from './fieldMapping';

export class Import {
    /**
    * The resource identifier returned from the POST to /resources. Resource referred to must be a valid CSV, XML, or JSON file.
    */
    'resourceId': string;
    /**
    * This defines the resource that will be created through this import process.
    */
    'importType': string;
    'importOptions': FieldMapping;
    /**
    * The type of contact import that is occurring.
    */
    'importMode': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "resourceId",
            "baseName": "resourceId",
            "type": "string"
        },
        {
            "name": "importType",
            "baseName": "importType",
            "type": "string"
        },
        {
            "name": "importOptions",
            "baseName": "importOptions",
            "type": "FieldMapping"
        },
        {
            "name": "importMode",
            "baseName": "importMode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Import.attributeTypeMap;
    }
}

